### ISSUE TITLE
creative and survival inventory bug

### ISSUE THREAD

**Issue by david21blox** [CrisXolt/Project-4JD-UI#34]
all the creative objects disappeared I don't know if they did something to make it happen but I have the texture that the objects had

**Comment by david21blox** [comment]
https://mega.nz/folder/5pYC0Q7b#FjWt1L5cUlkRqKBd7Ove8w

**Comment by CrisXolt** [comment]
I'm closing this because it's duplicated and because I'm about to update the files with full inventory UI in "Adaptive UI mode". Sorry, but you shouldn't post obsolete files (even if it has items, it's not well ordered for v1.19). Wait until I finish the "Museum UI" version if you want to use the creative UI more accurately.
